version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry-*"
      database:
        patterns:
          - "tortoise-orm"
          - "aerich"
          - "aiocache"
          - "asyncpg"
      webserver:
        patterns:
          - "fastapi"
          - "jinja2"
          - "python-multipart"
          - "uvicorn"
          - "httpx"
          - "pydantic-settings"
      auth:
        patterns:
          - "itsdangerous"
          - "argon2-*"
          - "joserfc"
      swu:
        patterns:
          - "libconf"
          - "semver"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: monthly
