# .readthedocs.yaml
version: 2

# Set the version of Python and other tools you might need
build:
    os: ubuntu-20.04
    tools: { python: "3.11" }
    jobs:
        pre_create_environment:
            - asdf plugin add poetry
            - asdf install poetry latest
            - asdf global poetry latest
            - poetry config virtualenvs.create false
        post_install:
            - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --only docs

mkdocs:
    configuration: mkdocs.yml
