repo_url: https://github.com/UpstreamDataInc/goosebit
repo_name: gooseBit
site_name: gooseBit
site_url: !ENV SITE_URL
theme:
  name: material
  logo: img/goosebit-logo.svg
  favicon: img/goosebit-logo.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to auto mode
markdown_extensions:
  - pymdownx.superfences
nav:
  - Home: index.md
  - Simple Stats Plugin: goosebit_simple_stats.md
  - Forwarded HTTP Header Plugin: goosebit_forwarded_header.md
