db_location: db.sqlite3
poll_time_default: 00:01:00
poll_time_registration: 00:00:10
poll_time_updating: 00:00:05
tenant: DEFAULT
metrics:
  prometheus:
    port: 9090
users:
  - email: admin@goosebit.local
    password: admin
    permissions:
      - "*"
logging:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
  loggers:
    tortoise:
      handlers: [ console ]
      level: WARNING
      propagate: yes
    aiosqlite:
      handlers: [ console ]
      level: WARNING
      propagate: yes
    multipart:
      handlers: [ console ]
      level: INFO
      propagate: yes
  root:
    level: INFO
    handlers: [ console ]
