## Settings to adjust for each installation

# Database to be used, default:
# db_uri: sqlite:///<project root>/db.sqlite3

# Path to the directory containing artifact files, default:
# artifacts_dir: /<project root>/artifacts

# Frequency that devices should check for available updates.
poll_time_default: 00:01:00

# Frequency to log information during an update. Defines how often download progress
# and device logs get updated.
poll_time_updating: 00:00:05

# User account for the frontend. Available permissions:
# "firmware.read", "firmware.write", "firmware.delete"
# "device.read", "device.write", "device.delete"
# "rollout.read", "rollout.write", "rollout.delete"
# "home.read"

users:
  - username: admin@goosebit.local
    password: admin
    permissions:
      - "*"
  - username: ops@goosebit.local
    password: ops
    permissions:
      - "home.read"

## Internal settings that usually don't need to be modified
poll_time_registration: 00:00:10
tenant: DEFAULT
metrics:
  prometheus:
    enable: false
logging:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
  loggers:
    tortoise:
      handlers: [console]
      level: WARNING
      propagate: yes
    aiosqlite:
      handlers: [console]
      level: WARNING
      propagate: yes
    multipart:
      handlers: [console]
      level: INFO
      propagate: yes
  root:
    level: INFO
    handlers: [console]
