volumes:
  db:
  artifacts:

services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pw
      POSTGRES_DB: goosebit
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U db_user -d goosebit
      interval: 4s
      timeout: 2s

  goosebit:
    image: goosebit
    build:
      context: ..
      args:
        GOOSEBIT_VERSION: 0.1.2
    environment:
      GOOSEBIT_DB_URI: postgres://db_user:db_pw@postgres:5432/goosebit
      GOOSEBIT_USERS: >-
        [{email="admin@goosebit.local", password="admin", permissions="*"}]
      GOOSEBIT_ARTIFACTS_DIR: /artifacts
    ports:
      - "8080:8080"
    volumes:
      - artifacts:/artifacts
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.27.0-alpine
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/certs:/certs
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - goosebit
