name: PyPI

on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'docsrc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Publish GH release
        uses: softprops/action-gh-release@v2.0.6
      - name: Build using poetry and publish to PyPi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_API_KEY }}
